resource_labels = { "provider" : "jx" }
jx_git_url = "https://github.com/AlbertGoma-LFS268-CICD-JenkinsX/cluster"
gcp_project = "lfs268-411509"
gsm = true
cluster_location = "europe-west1-b"
bucket_location = "EU"
kuberhealthy = false
force_destroy = true
node_spot = true
release_channel = "REGULAR"
delete_protect = false